import { createHash, randomUUID } from "node:crypto";
import { appendFile, mkdir, readFile } from "node:fs/promises";
import path from "node:path";
import { workspaceEvolutionPluginAuthoringJobsFile } from "../storage/paths.js";
import type { PluginAuthoringJob } from "../../shared/contracts/evolution.js";
interface JobEvent { eventId: string; commandId: string; job: PluginAuthoringJob }
const queues = new Map<string, Promise<void>>();

export class PluginAuthoringJobStore {
  constructor(private readonly workspaceRoot: string, private readonly now: () => Date = () => new Date()) {}
  async enqueue(commandId: string, bindingId: string, practiceId: string, practiceVersion: number, maxAttempts = 3): Promise<PluginAuthoringJob> { return this.exclusive(async () => { const events = await this.read(); const replay = events.find((item) => item.commandId === commandId); if (replay) return replay.job; const existing = [...(await this.project(events)).values()].find((item) => item.bindingId === bindingId && item.status !== "dead_letter"); if (existing) return existing; const timestamp = this.now().toISOString(); const job: PluginAuthoringJob = { jobId: `plugin_author_${hash(`${bindingId}:${practiceId}:${practiceVersion}`).slice(0, 32)}`, commandId, bindingId, practiceId, practiceVersion, status: "pending", attempts: 0, maxAttempts, createdAt: timestamp, updatedAt: timestamp }; await this.append(commandId, job); return job; }); }
  async claim(jobId: string): Promise<PluginAuthoringJob | undefined> { return this.exclusive(async () => { const current = (await this.project(await this.read())).get(jobId); if (!current || !["pending", "retry_wait"].includes(current.status) || (current.nextAttemptAt && Date.parse(current.nextAttemptAt) > this.now().getTime())) return undefined; const next: PluginAuthoringJob = { ...current, status: "running", attempts: current.attempts + 1, updatedAt: this.now().toISOString(), nextAttemptAt: undefined }; await this.append(`claim:${jobId}:${next.attempts}`, next); return next; }); }
  async succeed(jobId: string, candidateId: string): Promise<PluginAuthoringJob> { return this.finish(jobId, { status: "succeeded", candidateId, lastError: undefined, nextAttemptAt: undefined }); }
  async fail(jobId: string, message: string, terminal = false): Promise<PluginAuthoringJob> { const current = await this.get(jobId); const exhausted = current.attempts >= current.maxAttempts; return this.finish(jobId, { status: terminal || exhausted ? "dead_letter" : "retry_wait", lastError: message.slice(0, 1000), ...(!terminal && !exhausted ? { nextAttemptAt: new Date(this.now().getTime() + 60_000 * current.attempts).toISOString() } : {}) }); }
  async list(): Promise<PluginAuthoringJob[]> { return [...(await this.project(await this.read())).values()].sort((a, b) => a.createdAt.localeCompare(b.createdAt)); }
  async get(jobId: string): Promise<PluginAuthoringJob> { const item = (await this.project(await this.read())).get(jobId); if (!item) throw new Error("Plugin authoring job not found"); return item; }
  private async finish(jobId: string, patch: Partial<PluginAuthoringJob>): Promise<PluginAuthoringJob> { return this.exclusive(async () => { const current = (await this.project(await this.read())).get(jobId); if (!current) throw new Error("Plugin authoring job not found"); const next = { ...current, ...patch, updatedAt: this.now().toISOString() }; await this.append(`finish:${jobId}:${current.attempts}:${patch.status}`, next); return next; }); }
  private async project(events: JobEvent[]): Promise<Map<string, PluginAuthoringJob>> { const values = new Map<string, PluginAuthoringJob>(); for (const event of events) values.set(event.job.jobId, event.job); return values; }
  private async read(): Promise<JobEvent[]> { try { return (await readFile(workspaceEvolutionPluginAuthoringJobsFile(this.workspaceRoot), "utf8")).split(/\r?\n/).filter(Boolean).map((line) => JSON.parse(line) as JobEvent); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return []; throw error; } }
  private async append(commandId: string, job: PluginAuthoringJob): Promise<void> { const file = workspaceEvolutionPluginAuthoringJobsFile(this.workspaceRoot); await mkdir(path.dirname(file), { recursive: true }); await appendFile(file, `${JSON.stringify({ eventId: randomUUID(), commandId, job })}\n`, { encoding: "utf8", mode: 0o600, flush: true }); }
  private async exclusive<T>(operation: () => Promise<T>): Promise<T> { const key = path.resolve(workspaceEvolutionPluginAuthoringJobsFile(this.workspaceRoot)).toLowerCase(); const previous = queues.get(key) ?? Promise.resolve(); const pending = previous.catch(() => undefined).then(operation); const settled = pending.then(() => undefined, () => undefined); queues.set(key, settled); return pending.finally(() => { if (queues.get(key) === settled) queues.delete(key); }); }
}
function hash(value: string): string { return createHash("sha256").update(value, "utf8").digest("hex"); }
